apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp-dep
    labels:
        env: prac
spec:
    selector:
        matchLabels:
            env: prod
    replicas: 3
    template:
        metadata:
          name: nginx-pod
          labels:
              env: prod
        spec:
          containers:
              - name: nginx
                image: nginx