apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: RS-httpd-frontend
    labels:
        app: httpd-frontend-rs
spec:
    selector:
        matchLabels:
            app: httpd-frontend
    replicas: 3
    template:
      metadata:
        name: httpd-frontend
        labels:
          app: httpd-frontend
      spec:
        containers:
        - name: httpd-frontend
          image: httpd:2.4-alpine
